export const {
  NEXT_PUBLIC_POSTHOG_KEY,
  NEXT_PUBLIC_POSTHOG_HOST,
  OPENAI_API_KEY,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME,
  NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET,
  QSTASH_TOKEN,
  UPSTASH_WORKFLOW_URL,
  NEXT_PUBLIC_API_URL,
  NEXT_PUBLIC_BASE_URL,
  MP_ACCESS_TOKEN,
  MP_APP_URL,
  MP_WH_SECRET
} = process.env

