export const {
  OPENAI_API_KEY,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  QSTASH_TOKEN,
  UPSTASH_WORKFLOW_URL,
  MP_ACCESS_TOKEN,
  MP_APP_URL,
  MP_WH_SECRET,
  CLERK_SECRET_KEY,
  CLERK_WH_SECRET,
  TURSO_DATABASE_URL,
  TURSO_AUTH_TOKEN,
  KNOCK_SECRET_KEY
} = process.env

