export const {
  NEXT_PUBLIC_POSTHOG_KEY,
  NEXT_PUBLIC_POSTHOG_HOST,
  NEXT_PUBLIC_API_URL,
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME,
  NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET,
  NEXT_PUBLIC_KNOCK_PUBLIC_API_KEY,
  NEXT_PUBLIC_KNOCK_FEED_CHANNEL_ID,
  NEXT_PUBLIC_BASE_URL
} = process.env